resources:

- repo: self
  clean: true

variables:

  SamplesBin: SamplesBin
  system.collectionId: ee8504d9-65a6-4f6c-85ed-0ad4265128ee
  system.debug: false
  system.definitionId: 612
  system.teamProject: WindowsAI
  WINDOWS_WINMD: C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17763.0\Windows.winmd

strategy:
  maxParallel: 8
  matrix:
    Release_x64:
      BuildPlatform: x64
      BuildConfiguration: Release
    Debug_x64:
      BuildPlatform: x64
      BuildConfiguration: Debug
    Release_x86:
      BuildPlatform: x86
      BuildConfiguration: Release
    Debug_x86:
      BuildPlatform: x86
      BuildConfiguration: Debug

# specific branch build
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Samples

steps: 
  - task: PowerShell@2
    displayName: 'Check SDK Version 17763 is present'
    inputs:
      targetType: inline
      script: dir "${ENV:programfiles(x86)}\windows Kits\10\include\10.0.17763.0\"
    
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.1.300'
    inputs:
      version: 2.1.300
    condition: succeededOrFailed()

  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.9.2'
    inputs:
      versionSpec: 4.9.2
    condition: succeededOrFailed()

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    condition: succeededOrFailed()

  - task: PowerShell@2
    displayName: 'Create PFX key for signing APPX/MSIX bundles'
    inputs:
      targetType: inline
      script: $CertPath = 'SharedContent/shared_key.pfx';
              $CertPassword = ConvertTo-SecureString -String "MyPassword" -Force -AsPlainText;
              $cert = New-SelfSignedCertificate -Type Custom -Subject "orlevari" -KeyUsage DigitalSignature -FriendlyName "uitest-sign" -CertStoreLocation "Cert:\LocalMachine\My";
              Export-PfxCertificate -cert "Cert:\localmachine\my\$($cert.Thumbprint)" -FilePath $CertPath -Password $CertPassword;
    condition: succeededOrFailed()

  - task: VSBuild@1
    displayName: 'Build FNSCandyStyleTransfer-UWP-CS'
    inputs:
      solution: Samples/FNSCandyStyleTransfer/UWP/CS/snapcandy.sln
      vsVersion: 15.0
      msbuildArgs: '/p:PackageCertificateKeyFile=$(Build.Repository.LocalPath)\SharedContent\shared_key.pfx -v:diag  /p:OutDir=$(System.DefaultWorkingDirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)\'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      msbuildArchitecture: x64
      createLogFile: true
    condition: succeededOrFailed()

  - task: VSBuild@1
    displayName: 'Build AdapterSelection Sample '
    inputs:
      solution: Samples/AdapterSelection/AdapterSelection.sln
      vsVersion: 15.0
      msbuildArgs: '/p:AppxPackageSigningEnabled=false -v:diag /p:OutDir=$(System.DefaultWorkingDirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)\'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      msbuildArchitecture: x64
      createLogFile: true
    condition: succeededOrFailed()

  - task: VSBuild@1
    displayName: 'Build CustomOperatorCPU Sample '
    inputs:
      solution: Samples/CustomOperatorCPU/desktop/cpp/custom-operator-cpu-sample.sln
      vsVersion: 15.0
      msbuildArgs: '/p:AppxPackageSigningEnabled=false -v:diag /p:OutDir=$(System.DefaultWorkingDirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)\'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      msbuildArchitecture: x64
      createLogFile: true
    condition: succeededOrFailed()


  - task: VSBuild@1
    displayName: 'Build MNIST-Tutorial-cs'
    inputs:
      solution: 'Samples/MNIST/Tutorial/cs/mnist_demo.sln'
      vsVersion: 15.0
      msbuildArgs: '/p:AppxPackageSigningEnabled=false -v:diag /p:OutDir=$(System.DefaultWorkingDirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)\'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      msbuildArchitecture: x64
      createLogFile: true
    condition: succeededOrFailed()

  - task: VSBuild@1
    displayName: 'Build MNIST-UWP-cs'
    inputs:
      solution: 'Samples/MNIST/UWP/cs/mnist_demo.sln'
      vsVersion: 15.0
      msbuildArgs: '/p:AppxPackageSigningEnabled=false -v:diag'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      msbuildArchitecture: x64
      createLogFile: true
    condition: succeededOrFailed()

  - task: VSBuild@1
    displayName: 'Build SqueezenetObjectDetection'
    inputs:
      solution: Samples/SqueezeNetObjectDetection/squeezenetobjectdetection.sln
      vsVersion: 15.0
      msbuildArgs: '/p:AppxPackageSigningEnabled=false -v:diag /p:OutDir=$(System.DefaultWorkingDirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)\'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      msbuildArchitecture: x64
      createLogFile: true
    condition: succeededOrFailed()

  - task: VSBuild@1
    displayName: 'Build FNSCandyStyleTransfer-UWP-CS'
    inputs:
      solution: Samples/FNSCandyStyleTransfer/UWP/CS/snapcandy.sln
      vsVersion: 15.0
      msbuildArgs: '/p:AppxPackageSigningEnabled=false -v:diag  /p:OutDir=$(System.DefaultWorkingDirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)\'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      msbuildArchitecture: x64
      createLogFile: true
    condition: succeededOrFailed()

  - task: VSBuild@1
    displayName: 'Build MNIST-UWP-cppcx '
    inputs:
      solution: 'Samples/MNIST/UWP/cppcx/mnist_cppcx.sln'
      vsVersion: 15.0
      msbuildArgs: '/p:AppxPackageSigningEnabled=false -v:diag /p:OutDir=$(System.DefaultWorkingDirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)\'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      msbuildArchitecture: x64
      createLogFile: true
    condition: succeededOrFailed()

  - task: VSBuild@1
    displayName: 'Build CustomTensorization Sample'
    inputs:
      solution: Samples/CustomTensorization/CustomTensorization.sln
      vsVersion: 15.0
      msbuildArgs: '/p:AppxPackageSigningEnabled=false -v:diag /p:OutDir=$(System.DefaultWorkingDirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)\'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      msbuildArchitecture: x64
      createLogFile: true
    condition: succeededOrFailed()

  - task: VSBuild@1
    displayName: 'Build Emoji Sample'
    inputs:
      solution: Samples/Emoji8/UWP/cs/Emoji8.sln
      vsVersion: 15.0
      msbuildArgs: '/p:AppxPackageSigningEnabled=false -v:diag /p:OutDir=$(System.DefaultWorkingDirectory)\bin\$$(BuildPlatform)\$(BuildConfiguration)\'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      msbuildArchitecture: x64
      createLogFile: true
    condition: succeededOrFailed()

  - task: CopyFiles@2
    inputs:
      targetFolder: '$(Build.ArtifactStagingDirectory)\$(BuildPlatform)\$(BuildConfiguration)\'
      sourceFolder: '$(System.DefaultWorkingDirectory)\bin\$(BuildPlatform)\$(BuildConfiguration)\'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Samples'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: WinMLPublicSamples
    condition: succeededOrFailed()
